apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::982054244334:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::982054244334:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AXY6I72HIMTJ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-03T13:48:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "870"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d89d10c5-2274-4188-a89d-e510a4b806de
